using System;
using Sample.Models.Interfaces;

namespace Sample.Models.Data.DTO
{
    /// <summary>
    /// This can be auto generated by DtoMapper.tt
    /// </summary>
    [Serializable]
    public partial class AddressDTO : IDTO<AddressDTO, Address>
    {
        public int Id { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }

        public AddressDTO MapFrom(Address n)
        {
            return new AddressDTO
            {
                Id = n.Id,
                AddressLine1 = n.AddressLine1,
                AddressLine2 = n.AddressLine2,
                City = n.City,
                PostalCode = n.PostalCode
            };
        }

        public Address MapTo(AddressDTO n)
        {
            return new Address
            {
                Id = n.Id,
                AddressLine1 = n.AddressLine1,
                AddressLine2 = n.AddressLine2,
                City = n.City,
                PostalCode = n.PostalCode
            };
        }
    }
}